
[build]
  command = "npm run build"
  publish = ".netlify/output"
  base = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/next"

  [build.environment]
  NODE_VERSION = "18"

